### ISSUE TITLE
Support for TS-HTGL6FE

### ISSUE THREAD

**Issue by vKnmnn** [1000001101000/Debian_on_Buffalo#48]
Hi @1000001101000 

any chance this will run on this model?
the CPU is a ARM926EJ-Sid(wb) rev 0 (v5l) 
Hardware: MV-88fxx81
MemTotal:       126280 kB

I would just try it, but i don't know how to unbrick the device if something fails

**Comment by 1000001101000** [comment]
Good to hear from you!

That should work fine with the ts2pro installer files.

The process doesn't make any changes to the hardware/flash/etc so restoring the stock firmware is always possible if desired.

I've got a guide for that process here:
https://buffalonas.miraheze.org/wiki/Restoring_Stock_Firmware_without_TFTP

**Comment by vKnmnn** [comment]
alright, it booted fine and says Terastation arm installer on the display, put it doesn't seem to have network connectivity. no ICMP ping and no open port 22

**Comment by 1000001101000** [comment]
Nice!
The display code runs before the network detect/ssh stuff. That part takes a few minutes so it could be a timing thing.

**Comment by vKnmnn** [comment]
Yes, that might be the case. I'm running the installer now. 
Are there any hints on the partitioning? i didn't find it in the wiki.

**Comment by 1000001101000** [comment]
Actually yes.

I beleive for this device you need to make the root partition bigger than the stock firmware did. 2G works but i’d recommend more like 5G.

There are strict requirements for /boot that are mentioned in the instructions as well.

**Comment by vKnmnn** [comment]
sadly the installer died on me while deleting partitions and creating the first md for /boot and now hangs on 52% forever. i am left unable to create partitions so i think i'll have to partition one of the drives with another machine so i can get a booting system again.

**Comment by vKnmnn** [comment]
This is a tough device to work on. A few more restarts and i was able to create a swap partition. Problems went away then.
Installation is running now.

I saw you mentioned something about the XOR offloading that you wanted to add for the kernel. Have you made any progress there?

**Comment by 1000001101000** [comment]
Edit: the E04 message most likely means there was something wrong with your /boot. Could you post the details of your partitions/md devices?

 I may need to add some code to the installer to enable swap early to try to help prevent running out of memory like that. Devices with 64mb need that to even make it to the partitioner but I haven’t seen that on 128mb devices personally.

For this device I determined the SoC does not have dedicated XOR hardware like most others. I was able to patch the kernel to enable it on the Terastation III though. Adding some other missing hardware for that device is among the things I’m working on.

**Comment by vKnmnn** [comment]
i partitioned my 4 hdds in the same way:
1G boot raid2    (md4)
1G swap raid10 (md5)
8G /        raid1   (md2)
490G  /mnt/array1 raid5 (md3)

i remember unmounting /boot when the partitioning was finished, to write the ext3 again with the correct inode size, assuming the installer wouldnt do that  automatically. that might have messed things up, right?

is there a way to supply a sort of PIT file, a partition table that the installer will apply automatically? navigating the installer is a pain on a slow device like that :)

i noticed some entries matching "xor" in the kernel log, so i assumed there would be an XOR chip.

**Comment by 1000001101000** [comment]
I adjusted the installer to automatically set the inode size, no manual steps are required anymore. Doing that will prevent your system from fully booting because you would end up with an fstab entry with the wrong uuid (unless you fixed that after reformatting the volume).

The device should still boot if that's the case, it would just hang before starting ssh/etc. Did you put the boot files back in place after you reformatted?

Also, some devices can't handle 1GB /boot volumes. I use 768MB for my armel devices to avoid that issue.

**Comment by vKnmnn** [comment]
The Tera station did boot with a 1G boot partition before, so that's not the culprit here.

I did not recreate any file on /boot, because I did the modifications right after partitioning, when the installer was initializing.
I expected the boot configuration to happen last. So right now my boot partition is in am unknown state. It exists but I dont know what's on it. 

You have any idea how I can mount the boot partition now, to put the kernel there?

**Comment by 1000001101000** [comment]
I'm not exactly sure what would happen in that scenario. likely depends on whether you re-mounted it before it needed it etc.

How to fix it depends a bit on what you have available. I would probably just load the installer and run through it again.

You could probably load the installer, run it to the partitioning menu so it detects disks, then use it to chroot into the environment, mount /boot in the right place, fix fstab and then run update-initramfs to generate new boot files, then unmount and reboot. In theory that would set things right.

**Comment by vKnmnn** [comment]
That sounds like a good way to go. The trouble is, though, that I can only boot the installer if I destroy one of the raid1 partitions and put a file system on it.

**Comment by 1000001101000** [comment]
you could boot into it via TFTP to avoid that, though that may be a bigger pain.

**Comment by 1000001101000** [comment]
Also, you’ll want /boot, / and swap to all be raid1

**Comment by vKnmnn** [comment]
Alright, i have the installer running again.
RAID1 for all mountpoints except the big partition.

now the finish-installation part goes wrong: 
```
May 25 21:39:00 flash-kernel-installer: error: flash-kernel failed
May 25 21:39:00 main-menu[4262]: (process:22597): dpkg-divert: warning: diverting file '/sbin/st
art-stop-daemon' from an Essential package with rename is dangerous, use --no-rename
May 25 21:39:00 main-menu[4262]: (process:22597): dpkg-divert: warning: diverting file '/sbin/st
art-stop-daemon' from an Essential package with rename is dangerous, use --no-rename
May 25 21:39:00 main-menu[4262]: (process:22597): dpkg-divert: warning: diverting file '/sbin/st
art-stop-daemon' from an Essential package with rename is dangerous, use --no-rename
May 25 21:39:00 main-menu[4262]: WARNING **: Configuring 'flash-kernel-installer' failed with er
ror code 1
May 25 21:39:00 main-menu[4262]: WARNING **: Menu item 'finish-install' failed.

```

**Comment by 1000001101000** [comment]
could you post the output of `cat /proc/cpuinfo`?

**Comment by vKnmnn** [comment]
```
~ # cat /proc/cpuinfo 
processor       : 0
model name      : Feroceon rev 0 (v5l)
BogoMIPS        : 333.33
Features        : swp half thumb fastmult vfp edsp 
CPU implementer : 0x41
CPU architecture: 5TEJ
CPU variant     : 0x0
CPU part        : 0x926
CPU revision    : 0

Hardware        : Buffalo Terastation Pro II/Live
Revision        : 0000
Serial          : 0000000000000000
```

**Comment by 1000001101000** [comment]
could you try manually running flash-kernel and see what happens?

```
chroot /target /bin/bash
flash-kernel

```

**Comment by vKnmnn** [comment]
Yes, i will. currently i'm reinstalling, again :)
should be ready in 15 minutes.

**Comment by 1000001101000** [comment]
If you still have trouble I can try running an install on mine for comparison. 

I actually ran through it with this model fairly recently since this is typically the device I use for testing since it's the only one of this architecture I have with a serial console. Still, I made some changes recently for the 64mb ram devices and could have broken something without noticing (I guess).

**Comment by vKnmnn** [comment]
Right, it failed again.
I chrooted to target and ran flash-kernel. /proc wasn't mounted.
bind-mounted proc and repeated the step, flash-kernel exits without output and exitcode 2.

**Comment by vKnmnn** [comment]
I am not sure what flash-kernel is doing, but it compares the machine name from /proc/cpuinfo with Variations of the Hardware names.
But none of these match `Buffalo Terastation Pro II/Live`:
```
Machine: Buffalo Linkstation LS-CHLv2
Machine: Buffalo Linkstation LS-QVL
Machine: Buffalo Linkstation LS-VL
Machine: Buffalo Linkstation LS-WSXL
Machine: Buffalo Linkstation LS-WTGL
Machine: Buffalo Linkstation LS-WVL
Machine: Buffalo Linkstation LS-WVL/VL
Machine: Buffalo Linkstation LS-WXL
Machine: Buffalo Linkstation LS-WXL/WSXL
Machine: Buffalo Linkstation LS-XHL
Machine: Buffalo Linkstation LiveV3 (LS-CHL)
Machine: Buffalo Linkstation Mini
Machine: Buffalo Linkstation Mini (LS-WSGL)
Machine: Buffalo Linkstation Pro/Live
Machine: Buffalo/Revogear Kurobox Pro
```

**Comment by vKnmnn** [comment]
which means, the corresponding entry for Terastation 2 Pro is not available in /usr/share/flash-kernel/db/all.db

**Comment by 1000001101000** [comment]
You should also see my buffalo_devices.db with an entry for this device. Usually “machine not found” is a pretty straightforward error message.

Could you output ls /boot or ls /target/boot

**Comment by vKnmnn** [comment]
nothing there
```
root@debian:/# ls -a /usr/share/flash-kernel/db 
.  ..  all.db
root@debian:/# ls -a /boot/
.  ..  lost+found
```

**Comment by 1000001101000** [comment]
Ah, looks like I probably broke something. Flash-kernel is triggering earlier than it should.

Let me run through it on mine and figure out the issue.

**Comment by vKnmnn** [comment]
i manually copied buffalo_devices.db from sources directory but flash-kernel still seems to fail. 
I'll wait for your feedback.

**Comment by vKnmnn** [comment]
the entry for Buffalo Terastation Pro II/Live is missing the DTB-Id field.

**Comment by 1000001101000** [comment]
That’s actually intentional, this SoC never got DTB support. It uses the older “machine id” method along with hardware support built into the kernel a long time ago.

**Comment by vKnmnn** [comment]
ah i see. so the script fails on the check ` test -e /boot/vmlinuz* `

**Comment by 1000001101000** [comment]
Yeah. Normally the debian installer would just install the default kernel then run flash-kernel. Mine is supposed to skip that step so that it can choose which kernel to install later. It looks like I messed that part up somehow.

**Comment by vKnmnn** [comment]
yes, i saw in the logs, it tried to find a suitable kernel to install and couldn't find one

**Comment by 1000001101000** [comment]
Is this buster or stretch?

**Comment by vKnmnn** [comment]
Buster

**Comment by 1000001101000** [comment]
I just ran through a Buster install on my TS-HTGL using the installer and kernel downloaded straight from github. I didn't run into any errors.

I could understand if it failed randomly due to a momentary network issue but I believe you said you tried twice and ran into the same thing. 

At this point I would recommend downloading a fresh copy of the installer files (just in case) and starting the install again. If you hit the issue again download the /var/log/syslog and post it.

**Comment by 1000001101000** [comment]
![image](https://user-images.githubusercontent.com/38921757/82852929-d822dd00-9ec9-11ea-87b5-8b47a3ed9feb.png)

**Comment by vKnmnn** [comment]
Starting a new install now.

**Comment by vKnmnn** [comment]
I ran a new installation of Buster with the latest initrd and uImage from github: 
```
$ sha256sum initrd.buffalo uImage.buffalo.ts2pro 
85c7ec7bab04154d45e95cf7f5d56fe093f886af5f4772c9aa993ed75f657aa5  initrd.buffalo
b7eb685b5d7989eee501dce6669341ebdb58dead0347cc29ff52ec0ab8c0bc21  uImage.buffalo.ts2pro
```
Here's a few things i noticed:
- kernel 4.19 gets installed and configured, then is deleted later. there could be time saved here.
- shortly before flash-kernel gets run, there's a command that changes the display on the station to alternate between `Terastation arm Debian Installer` and `System Now Shutting Down` which is a bit early, because there are still more steps to be done and the device isn't actually shutting down.
- the installer downloads from US-Mirrors, now matter where we are, which sometimes results in very slow speeds.


I think part of what went wrong before is that somewhere, the automatic installer had an error occur and dropped to the advanced installer, which doesn't seem to be handling that case well in regards to the modifications you made (extra packages and such)

nevertheless, on the first boot after installing, the installer boots again.
so i take out the drive where the installer is on.
then i get `Loading Kernel` for about 5 minutes, before showing `E04` again.
now i'm trying to repair the boot partition.

**Comment by vKnmnn** [comment]
Okay, i have successfully rebuilt the raid and i have a successful boot.

where does this leave us?

**Comment by 1000001101000** [comment]
That mostly makes sense. I have seen the installer fail because of network/timeout issues once or twice in testing. It seems like most of the apt-get type commands don't have any retry logic. 

I really hate having to hard-code the mirrors but the ssh based installer requires a mirror is set so that it can download components required to start ssh/etc. You could always build your own images using my scripts and change the hardcoded mirror (I don't know if anyone has tried that yet)

unfortunately taking a while to boot is normal for these devices. If you watch the serial console you can see that this is mostly uboot loading and searching each drive for boot files then finally loading and booting them from a drive. The actual boot process for debian goes pretty fast. Actually, now that you fixed your swap issue it should go faster, I think by default it will wait 90 seconds if fails to detect the swap device before moving on with out it

I don't understand what happened to your swap, I hope that hasn't been happening to others without them noticing. 

The on-board microcontroller decides whether the device powers back on after being shutdown, this means you have to send it a command to tell it you want to restart rather than shutdown at the end of the install process. That command also adds the shutting down message. I'm currently run it in the last custom script of the install process which is why it displays for so long. I might be able to move it to the actual shutdown scripts to prevent that in the future.

I never did find a method to prevent it from installing the default kernel, instead I added logic to uninstall it and replace it with the custom kernel for devices that need one. All The Terastation-III devices need one because they aren't supported in the default kernel. The Terastation-II needs one for Buster because Orion5x PCI support is broken in kernels after 4.12 (they completely overhauled PCI in 4.13) . They actually broke the ethernet driver at about the same time then fixed it in ~5.4, my custom kernel includes a patch that fixes it.

The path issue is normal for Debian Buster. Presumably for security reasons regular users don't have sbin on their path.

Sounds like you're up and running. Let me know if you run into anything else I can help with.

**Comment by vKnmnn** [comment]
Thanks for giving these details, that's very helpful.

I had started the installation of OpenMediaVault and left it running. I just came back home to hear the device beeping it's E04 message again...

so i attached one of the disks to another computer to see the contents of /boot
```
$ sha256sum .mnt/*
657d3a8b9911a339f027b57c3f1048e6301bd40b31a969757f40ad89e70f7e61  .mnt/config-4.12.13
2eb6b71e84697f7119ad962b3d63fd6b9d134cc0d3f5d52816ac3278059ee59c  .mnt/initrd.buffalo
20d46b5a59e26d794304073f494e3893cb9af29f33149f4f504ea6ac3948f705  .mnt/initrd.img-4.12.13
cf0e80d624fea392c3e4a8273975a4398caed29b071181d8e9dc9fcc6c02ff9d  .mnt/System.map-4.12.13
32ce360253430af6e2bcc862ceb0921384378132c572bedda21c6dab44b1252a  .mnt/uImage.buffalo
8bfaa601ef4c9e5e38f868687040636d1eaa5e25ab065bebb8d472f62ea8fd1b  .mnt/vmlinuz-4.12.13

657d3a8b9911a339f027b57c3f1048e6301bd40b31a969757f40ad89e70f7e61  .mnt/config-4.12.13
2eb6b71e84697f7119ad962b3d63fd6b9d134cc0d3f5d52816ac3278059ee59c  .mnt/initrd.buffalo
20d46b5a59e26d794304073f494e3893cb9af29f33149f4f504ea6ac3948f705  .mnt/initrd.img-4.12.13
cf0e80d624fea392c3e4a8273975a4398caed29b071181d8e9dc9fcc6c02ff9d  .mnt/System.map-4.12.13
32ce360253430af6e2bcc862ceb0921384378132c572bedda21c6dab44b1252a  .mnt/uImage.buffalo
8bfaa601ef4c9e5e38f868687040636d1eaa5e25ab065bebb8d472f62ea8fd1b  .mnt/vmlinuz-4.12.13
```

that looks alright to me. why did it die again?

**Comment by vKnmnn** [comment]
Also, i don't get any output on the serial port. Am i using the wrong settings? I'm on 115200, 8N1, NOR, VT102

**Comment by 1000001101000** [comment]
That looks alright to me too. 

Randomly shutting off and beeping like that typically means the watchdog timer was not disabled properly at startup. I've put a fair amount of work to try to make that process bullet-proof but it sounds like it failed. Next time you boot run `systemctl status micon_boot.service` to see the status of that service. I'd be interested to know if it just failed randomly (it's supposed to retry a lot of times before giving up) or if OMV/etc messed up the python dependencies etc.

I've been thinking of adding logic to have it send the signal in the initrd to make it even more reliable. I've actually got a script that does that and also enables the serial console that I haven't added to the installer if you're interested. I haven't decided what to do with it yet since some folks might want to use that serial port for something else I haven't made it a default.

Here are my minicom settings:
```
+-----------------------------------------------------------------------+                 
| A -    Serial Device      : /dev/ttyUSB0                              |                 
| B - Lockfile Location     : /var/lock                                 |                 
| C -   Callin Program      :                                           |                 
| D -  Callout Program      :                                           |                 
| E -    Bps/Par/Bits       : 115200 8N1                                |                 
| F - Hardware Flow Control : Yes                                       |                 
| G - Software Flow Control : No                                        |                 
|                                                                       |                 
|    Change which setting?                                              |                 
+-----------------------------------------------------------------------+ 
```

**Comment by 1000001101000** [comment]
The watchdog timer on this device is only a few minutes, which is frustrating but at least gives an error message reasonably quickly. On the TS3400 series the timer is set to 4 hours and triggers a silent reboot. It took me months to notice and understand what was happening. 

I didn't know anything about the older devices at the time. I ended up writing the python library to deal with it before realizing others had already dealt with this via micro-evtd and custom kernel code. Although I'm fond of the python library I should probably re-work the startup process to use micro-evtd which seems more reliable overall.

**Comment by vKnmnn** [comment]
Do you know of a way to get the tftp-boot process to work from linux? it's a real pain having to take out the hdd everytime something goes wrong and resyncing the array.

i saved the omv-install log. it doesn't seem like an unplanned shutdown. the omv-setup did it, i think.
[omv-install.log](https://github.com/1000001101000/Debian_on_Buffalo/files/4683660/omv-install.log)

Now i'm working on getting it back to booting, hoping i don't have to reinstall yet again.

**Comment by vKnmnn** [comment]
aha! now that i have the serial console i can see that the kernel does boot indeed, so the boot partition is still alright.
but the machine is running out of memory on boot! So maybe the swap partition still doesn't get mounted.
```
Out of memory: Kill process 244 (systemd-network) score 5 or sacrifice child
[   45.043177] Killed process 244 (systemd-network) total-vm:14588kB, anon-rss:644kB, file-rss:0kB, shmem-rss:0kB

```

**Comment by 1000001101000** [comment]
might explain why the watchdog script is failing too. 

I've been using an initramfs hook script to activate swap before starting the system to avoid that type of issue. I usually only run into it when test installer images becuase I end up changing the UUID of the swap partition. I don't know you keep running into this but I think that script could help you too.

I'll post that and the serial console script along with setup instructions in a little bit.

**Comment by 1000001101000** [comment]
I added the files to Tools/
copy install-micro-evtd /etc/initramfs-tools/hooks/
copy enable_serial.sh /etc/initramfs-tools/scripts/init-top/
copy early_swap.sh to /etc/initramfs-tools/scripts/init-bottom/

then run `initramfs-update -u`

**Comment by vKnmnn** [comment]
i had to change `MODULES=dep` to `MODULES=most` in `/etc/initramfs-tools/conf.d/modules` in order to run `update-initramfs -u`

the early_swap script of course throws a bunch of errors due to missing devices, i suppose that can be ignored. maybe we can test if we're actually in an initramfs-session and only then run the script? I'm not sure if i understood that script's purpose well enough. It's not really supposed do be run by update-initramfs, right?

anyway, upon reboot, the initrd is broken, doesn't get recognized by u-boot. I'm in tftp mode now.

**Comment by 1000001101000** [comment]
without `MODULES=dep` the resulting initrd will be too big boot on this device. What error made you change that?

all the rest can be ignored, I had actually forgotten about that part. I don't know why it executes that stuff when adding to the initramfs, I can probably add some logic to suppress the errors and/or figure out how to make it stop doing that.

**Comment by vKnmnn** [comment]
first it fails, because sys and proc aren't mounted in chroot. then, when they're mounted, this happens:

```
root@debian:/# update-initramfs -u
update-initramfs: Generating /boot/initrd.img-4.12.13
mkinitramfs: failed to determine device for /
mkinitramfs: workaround is MODULES=most, check:
grep -r MODULES /etc/initramfs-tools

Error please report bug on initramfs-tools
Include the output of 'mount' and 'cat /proc/mounts'
update-initramfs: failed for /boot/initrd.img-4.12.13 with 1.
```

**Comment by 1000001101000** [comment]
that's weird. could you post /proc/mounts?

**Comment by 1000001101000** [comment]
...this may be corrected by mounting /dev/ as well. I thought it was a different error in that case.

`mount -o bind /dev /target/dev`

**Comment by vKnmnn** [comment]
i was able to pull out the syslog of the installed system. I'll put it here, in case you wanna take a look at it.
[terastation_syslog.log](https://github.com/1000001101000/Debian_on_Buffalo/files/4684707/terastation_syslog.log)

I think that the systemd service file for micon is broken and that's why it shutdown. 
```May 26 15:38:45 debian systemd[1]: /etc/systemd/system/micon_boot.service:5: Unknown lvalue 'Restart' in section 'Unit', ignoring
May 26 15:38:45 debian systemd[1]: /etc/systemd/system/micon_boot.service:6: Unknown lvalue 'RestartSec' in section 'Unit', ignoring```

this is /proc/mounts from chroot:
```
root@debian:/# cat /proc/mounts 
/dev/md2 / ext4 rw,relatime,data=ordered 0 0
/dev/md0 /boot ext3 rw,relatime,data=ordered 0 0
none /sys sysfs rw,relatime 0 0
none /proc proc rw,relatime 0 0
```
yes, the bind-mount of /dev helped. funny, that it warns about sys and proc not being mounted, but not dev :)

**Comment by 1000001101000** [comment]
that is funny. In some circumstances (or versions?) it specifically says that it could not find in /dev/disk-by-id/.... 

The systemd service being broken sounds troubling. Is your display being set with the debian version/etc?

**Comment by vKnmnn** [comment]
I'm on the next boot-cycle. the new initrd still doesn't do the trick. I'll try rebuilding it after removing those extra three files.

i'm not sure what you mean by the last sentence. When i had a successful boot of the system, it did say Terastation ARM Debian 10.4.

**Comment by vKnmnn** [comment]
I took a look at the service file. It has double Restart and RestartSec entries, but that shouldn't keep the service from running.
```
[Unit]
Description=Tell Terastation it finished booting so it doesnt shutdown
Wants=network-online.target
After=network-online.target
Restart=on-failure
RestartSec=30

[Service]
ExecStart=/usr/local/bin/micon_scripts/micon_startup.py
Restart=on-failure
RestartSec=30

[Install]
WantedBy=multi-user.target

```

**Comment by 1000001101000** [comment]
That's what I was asking, if the display is getting updated then the service is running successfully. I'll fix the duplicate entry to clear up those errors though.

**Comment by 1000001101000** [comment]
are you trying to build the initrd from a chroot in the installer? I would expect that to work without much issue (once you switch back to MODULES=dep).

**Comment by vKnmnn** [comment]
I'm running it right now. /run wasn't mounted too, so that's where the error might have come from, but i really have no idea. 
We'll see in a few minutes.

I wrote a little chroot helper, because it got annoying. maybe you wanna use it.
```
#!/bin/ash

if [[ -z "${1}" ]]; then
        echo "chroot where?"
        exit 1;
fi

chroot_dir=$(realpath "${1}")
echo $chroot_dir
for mountpoint in dev proc run sys; do
        mount -o bind /${mountpoint} ${chroot_dir}/${mountpoint}
done

chroot "${chroot_dir}" "${2:-/bin/bash}"

```

**Comment by vKnmnn** [comment]
And again:
```
** Unable to read "/initrd.buffalo" from ide 2:1 **
serch_boot_drv (240)>No init_file 2 
Using device ide3, partition 1
```
But now the initrd should be identical to the one i first had. i should have backed that up :)

**Comment by 1000001101000** [comment]
take a look at the size, that's usually the issue. I think the limit for this device is right around 7MB for initrd.

**Comment by vKnmnn** [comment]
```
-rw-r--r-- 1 root root 9553183 May 26 22:44 initrd.buffalo
-rw-r--r-- 1 root root 2063608 May 26 22:44 uImage.buffalo
```
i took away the extra files like early_swap and such. Also set MODULES to dep. shouldn't this then create a small initrd?

**Comment by 1000001101000** [comment]
They are specific to the UUID of the rootfs, mine wouldn't help.

take a look at the contents of yours and confirm whether the space is caused by excessive modules. then take a look at /etc/initramfs-tools/conf.d/modules and /etc/initramfs-tools/initramfs.conf. 

Usually when it doesn't obey my settings it's because I misspelled "MODULES". I'd probably change both the "dep" and try again.

**Comment by vKnmnn** [comment]
i can't lsinitramfs that file (initrd.buffalo) because `cpio: premature end of archive`
`/etc/initramfs-tools/initramfs.conf` contained another line with `MODULES=most`. Changing it to `dep` doesn't affect the size.
`/etc/initramfs-tools/modules` does not contain any modules.
The file `initrd.img-4.12.13`  is already pretty big: `-rw-r--r--    2 root     root        9.1M May 26 21:51 initrd.img-4.12.13
Where does that come from?
`

i'll rebuild it with `-v` to see what's in there.
[initramfs.log](https://github.com/1000001101000/Debian_on_Buffalo/files/4685219/initramfs.log)

**Comment by 1000001101000** [comment]
sorry, initrd.buffalo is the initrd with the uboot header added initrd.img-4.12.13 is the actual initrd.

it can be unpacked somewhere via
`zcat /boot/initrd.img-4.12.13 | cpio -mvid`

**Comment by 1000001101000** [comment]
just to confirm: are you booted into the installer (then chrooted to the system) when you are trying this? or some other method?

**Comment by 1000001101000** [comment]
you could also try XZ compression to get the size down and hopefully boot back into the system:

This is what I use:
```
root@ts2pro-Buster:~# cat /etc/initramfs-tools/conf.d/compress 
COMPRESS=xz
XZ_OPT=-2e
export XZ_OPT
```

**Comment by vKnmnn** [comment]
not a good idea running that command as root in /

i looked around and there are several big files
```
-rw-r--r--    1 root     root        2.0M Apr 20 22:23 libcrypto.so.1.1
-rwxr-xr-x    1 root     root        1.3M May  1  2019 libc-2.28.so
-rw-r--r--    1 root     root      736.6K Jan 20  2019 libgcrypt.so.20.2.4
-rw-r--r--    1 root     root      657.5K May  1  2019 libm-2.28.so
-rw-r--r--    1 root     root      637.4K Jan  5  2019 libzstd.so.1.3.8
-rw-r--r--    1 root     root      566.9K Apr 27 19:02 libsystemd.so.0.25.0
-rw-r--r--    1 root     root      448.3K Apr 20 22:23 libssl.so.1.1
-rw-r--r--    1 root     root      440.0K Jun 21  2019 libdevmapper.so.1.02.1
-rw-r--r--    1 root     root      417.3K Mar  7  2019 libpcre.so.3.13.3
-rw-r--r--    1 root     root      337.7K Mar 22  2019 libntfs-3g.so.883.0.0
-rw-r--r--    1 root     root      321.7K Jan 10  2019 libmount.so.1.1.0
-rw-r--r--    1 root     root      294.4K Jan 10 02:19 libext2fs.so.2.4
-rw-r--r--    1 root     root      289.9K Jan 10  2019 libblkid.so.1.1.0
-rw-r--r--    1 root     root      193.8K Mar 16  2019 libreadline.so.5.2
```
libcrypto is part of libssl. i suppose it came with some dependency of OMV

**Comment by vKnmnn** [comment]
Yes, i booted the installer via TFTP and chrooted to / on the Raid.
I've added the compress file. it's building right now.

**Comment by vKnmnn** [comment]
actually it's not building, because i messed up the installation my extracting that initramfs across my root file system...
Lots of Busybox-binaryies in my path now.
it's getting late, i'm getting careless.

**Comment by vKnmnn** [comment]
I will trigger a full reinstall and report back tomorrow.

**Comment by 1000001101000** [comment]
I’ll try to give better warnings about commands like cpio and tar in the future

**Comment by vKnmnn** [comment]
That's alright. It can happen. I've been on your heels all day, after all. Thanks for all your help so far, by the way.

**Comment by vKnmnn** [comment]
Ok, the installation went through, first boot failed, second boot worked.
I'm now directly in the running system and backed up the boot directory right away. swap was mounted fine, too.

I'm looking at journalctl and dmesg now to see if everything is running fine.

there's an error about cgroup2 and nsdelegate. According to a quick googling we have that message because we're using systemd>235 on kernel 4.12.13. It seems we're losing iptables-capabilities as a consequence.

then, there's the message about junk in initramfs. maybe we can save some space here. Do you know what's causing this?

also, ntp spits out some warnings about not being able to listen on some ipv6 interface. i'm too lazy to debug that, i just deactivated ipv6 for ntp.

The messages about the orion chip i think you mentioned already some lack of support for it, so that can be ignored.
```
May 27 10:02:48 debian kernel: Initramfs unpacking failed: junk in compressed archive

May 27 10:02:48 debian kernel: cgroup: cgroup2: unknown option "nsdelegate"

May 27 10:02:48 debian systemd[1]: File /lib/systemd/system/systemd-journald.service:12 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewa
May 27 10:02:48 debian systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
May 27 10:02:51 debian kernel: libphy: PHY orion-mdio-mii:00 not found
May 27 10:02:51 debian kernel: libphy: PHY orion-mdio-mii:01 not found
May 27 10:03:08 debian ntpd[380]: bind(23) AF_INET6 daba:daba:d000:0:216:1ff:fea5:c6fe#123 flags 0x11 failed: Cannot assign requested address
May 27 10:03:08 debian ntpd[380]: unable to create socket on eth0 (6) for daba:daba:d000:0:216:1ff:fea5:c6fe#123
```

I will now add the Serial script to the initramfs and see how that turns out and then install OMV again. wish me luck.

**Comment by vKnmnn** [comment]
The installation process for OMV crapped out in the very last bits. OOM condition, resulting in a reboot.
The swap partition was mounted, and i can actually reboot the thing, but it is slow as hell, i can hear the hdd swapping all the time, but i still get OOM-kills. i end up in emergency mode.

i think OMV might be just a bit too demanding for this little device. I'll try tweaking systemd a bit, to see if i can get it working.

**Comment by 1000001101000** [comment]
The systemd thing is disappointing. maybe someday some one will fix the PCI issue so we can move to a newer kernel, but there weren't that many orion5x devices with PCI to begin with and only a couple got mainline support. This was one of them and no one seems to have bothered to add it to flash-kernel until I did last year. This makes me think very few know/care about it, we should probably submit a bug somewhere.I spent some time looking at the source to search for a fix but don't really know where to start. 

The message about junk in the initramfs is a side effect of how the kernel paramters get passed. uboot loads it into a specific memory location and then the kernel reads the hardcoded parameter that tells it to load 15M from that address as the initrd. The "junk" is when it hits the end of the real initrd. More sophisticated boot loaders pass the actual initrd size which avoids this.

I suppose you could add more swap to avoid OOM but it wouldn't surprise me if OMV is just too much for the device. I'm somewhat disapointed there isn't something open-source designed to work on this type of device (if there is no one has mentioned it).

**Comment by vKnmnn** [comment]
The OMV-Setup's last step takes a big amount of RAM. I disabled the OOM-Killer and added n extra USB thumb drive as swap.
`sysctl vm.overcommit_memory=2`
That helps a lot, but obiously it does only as soon as / is mounted and the sysctl options read from file.

the installation went through.
Installation also triggered a rebuild of initramfs, which ended up being 9MB again, so i just replaced it with the backup.

I'm now testing with systemd mounting the swap as soon as possible, but even that might not help. the reason we get OOM is, that there exists memory that cannot be swapped out, because it is in use by the kernel. that's what the field "unreclaimable" tells us, when oom-killer prints on screen.

interestingly i am able to boot  as soon as i disconnect any one drive of the array. with all four connected i get OOM right before swap.target is reached. then the boot process proceeds veeeery slowly. 
Still working on it.

**Comment by 1000001101000** [comment]
admittedly, my focus in all of this has been to support as much hardware on as many devices as possible and make getting them running as simple as possible. This has had the side-effect of my mostly only confirming that I can get devices running and that they seem stable when mostly idle. 

I'm glad you're digging deeper into how to actually put the older devices to work (or at least where the limits are). Hopefully we end up with some insights we can add to the wiki.

**Comment by 1000001101000** [comment]
I like your thumb drive as temporary swap approach. I actually did the same with a java-heap on a server about a decade ago.

**Comment by vKnmnn** [comment]
regarding the thumb drive: now i went and used a SSD over usb. I wanted to see if latency and speed had a role in these errors.

I haven't gotten it to work yet. This issue with OOM when 4 drives attached is weird to figure out. Next, I will try if it's due to the raid5 on it.

Some questions:

- do you also have a warning in the kernel log when booting? it occurs after XOR probing. Log below.
- where can i change the kernel commandline embedded in the uboot image? i wanna try switching off the OOM killer from there.
- can you take a look at this and tell me what you think about the  differences of the initrds after installing OMV? 
- is there a way to find out -why- these extra files ended up in the initrd?
- are they really needed in the initrd? i suppose we could remove e.g. ntfs-3g because any ntfs device attached won't have to be available that early. similar for ldm. what do you think?
- is there a way to steal back the 20MB used by uboot?

using the conf.d/compress file get's the image down to 6.5M, so we can actually boot it. The lack of memory caused by that, after decompressing makes the boot process even more unstable though. I'll see what changes without raid5.
```
May 27 17:45:53 terastation kernel: xor: measuring software checksum speed
May 27 17:45:53 terastation kernel:    arm4regs  :   428.000 MB/sec
May 27 17:45:53 terastation kernel:    8regs     :   352.000 MB/sec
May 27 17:45:53 terastation kernel:    32regs    :   427.000 MB/sec
May 27 17:45:53 terastation kernel: xor: using function: arm4regs (428.000 MB/sec)
May 27 17:45:53 terastation kernel: ------------[ cut here ]------------
May 27 17:45:53 terastation kernel: WARNING: CPU: 0 PID: 128 at drivers/md/md.c:2278 set_in_sync+0x34/0xf8 [md_mod]
May 27 17:45:53 terastation kernel: Modules linked in: raid10 raid456 libcrc32c crc32c_generic async_raid6_recov async_memcpy async_pq async_xor xor async_tx raid6_pq raid0 multipath linear raid1 
May 27 17:45:53 terastation kernel: CPU: 0 PID: 128 Comm: md2_raid1 Not tainted 4.12.13 #3
May 27 17:45:53 terastation kernel: Hardware name: Buffalo Terastation Pro II/Live
May 27 17:45:53 terastation kernel: [<c00161d4>] (unwind_backtrace) from [<c0013140>] (show_stack+0x18/0x1c)
May 27 17:45:53 terastation kernel: [<c0013140>] (show_stack) from [<c0021004>] (__warn+0xe8/0x104)
May 27 17:45:53 terastation kernel: [<c0021004>] (__warn) from [<c00210dc>] (warn_slowpath_null+0x24/0x2c)
May 27 17:45:53 terastation kernel: [<c00210dc>] (warn_slowpath_null) from [<bf0bd5f0>] (set_in_sync+0x34/0xf8 [md_mod])
May 27 17:45:53 terastation kernel: [<bf0bd5f0>] (set_in_sync [md_mod]) from [<bf0c6ec8>] (md_check_recovery+0x324/0x5d8 [md_mod])
May 27 17:45:53 terastation kernel: [<bf0c6ec8>] (md_check_recovery [md_mod]) from [<bf0e61c4>] (raid1d+0x38/0x1540 [raid1])
May 27 17:45:53 terastation kernel: [<bf0e61c4>] (raid1d [raid1]) from [<bf0bd1d4>] (md_thread+0x188/0x190 [md_mod])
May 27 17:45:53 terastation kernel: [<bf0bd1d4>] (md_thread [md_mod]) from [<c003b1c0>] (kthread+0x124/0x13c)
May 27 17:45:53 terastation kernel: [<c003b1c0>] (kthread) from [<c000f710>] (ret_from_fork+0x14/0x24)
May 27 17:45:53 terastation kernel: ---[ end trace 8f6fda2324d7d0db ]---
May 27 17:45:53 terastation kernel: EXT4-fs (md2): mounted filesystem with ordered data mode. Opts: (null)
May 27 17:45:53 terastation systemd[1]: Inserted module 'autofs4'

```
```
Only in biginitrd/bin: btrfs
Only in biginitrd/bin: ntfs-3g
Only in biginitrd/conf/conf.d: compress
Only in biginitrd/conf/conf.d: zz-resume-auto
Files smallinitrd/conf/initramfs.conf and biginitrd/conf/initramfs.conf differ
Files smallinitrd/etc/ld.so.cache and biginitrd/etc/ld.so.cache differ
Only in biginitrd/etc: lvm
Files smallinitrd/etc/mdadm/mdadm.conf and biginitrd/etc/mdadm/mdadm.conf differ
Only in biginitrd/etc/modprobe.d: openmediavault.conf
Only in smallinitrd/: initrd.img-4.12.13
Only in biginitrd/: intrd
Only in biginitrd/lib/arm-linux-gnueabi: libaio.so.1
Only in biginitrd/lib/arm-linux-gnueabi: libaio.so.1.0.1
Only in biginitrd/lib/arm-linux-gnueabi: libdevmapper-event.so.1.02.1
Only in biginitrd/lib/arm-linux-gnueabi: libgcc_s.so.1
Only in biginitrd/lib/arm-linux-gnueabi: libgcrypt.so.20
Only in biginitrd/lib/arm-linux-gnueabi: libgcrypt.so.20.2.4
Only in biginitrd/lib/arm-linux-gnueabi: libgpg-error.so.0
Only in biginitrd/lib/arm-linux-gnueabi: libgpg-error.so.0.26.1
Only in biginitrd/lib/arm-linux-gnueabi: liblz4.so.1
Only in biginitrd/lib/arm-linux-gnueabi: liblz4.so.1.8.3
Only in biginitrd/lib/arm-linux-gnueabi: liblzo2.so.2
Only in biginitrd/lib/arm-linux-gnueabi: liblzo2.so.2.0.0
Only in biginitrd/lib/arm-linux-gnueabi: libntfs-3g.so.883
Only in biginitrd/lib/arm-linux-gnueabi: libntfs-3g.so.883.0.0
Only in biginitrd/lib/arm-linux-gnueabi: libreadline.so.5
Only in biginitrd/lib/arm-linux-gnueabi: libreadline.so.5.2
Only in biginitrd/lib/arm-linux-gnueabi: libsystemd.so.0
Only in biginitrd/lib/arm-linux-gnueabi: libsystemd.so.0.25.0
Only in biginitrd/lib/arm-linux-gnueabi: libtinfo.so.6
Only in biginitrd/lib/arm-linux-gnueabi: libtinfo.so.6.1
Only in biginitrd/lib/arm-linux-gnueabi: libz.so.1
Only in biginitrd/lib/arm-linux-gnueabi: libz.so.1.2.11
Only in biginitrd/lib/arm-linux-gnueabi: libzstd.so.1
Only in biginitrd/lib/arm-linux-gnueabi: libzstd.so.1.3.8
Only in biginitrd/lib/modules/4.12.13/kernel/drivers/md: dm-bufio.ko
Only in biginitrd/lib/modules/4.12.13/kernel/drivers/md: dm-log.ko
Only in biginitrd/lib/modules/4.12.13/kernel/drivers/md: dm-mirror.ko
Only in biginitrd/lib/modules/4.12.13/kernel/drivers/md: dm-raid.ko
Only in biginitrd/lib/modules/4.12.13/kernel/drivers/md: dm-region-hash.ko
Only in biginitrd/lib/modules/4.12.13/kernel/drivers/md: dm-snapshot.ko
Only in biginitrd/lib/modules/4.12.13/kernel/fs: fuse
Files smallinitrd/lib/modules/4.12.13/modules.alias and biginitrd/lib/modules/4.12.13/modules.alias differ
Files smallinitrd/lib/modules/4.12.13/modules.alias.bin and biginitrd/lib/modules/4.12.13/modules.alias.bin differ
Files smallinitrd/lib/modules/4.12.13/modules.dep and biginitrd/lib/modules/4.12.13/modules.dep differ
Files smallinitrd/lib/modules/4.12.13/modules.dep.bin and biginitrd/lib/modules/4.12.13/modules.dep.bin differ
Files smallinitrd/lib/modules/4.12.13/modules.devname and biginitrd/lib/modules/4.12.13/modules.devname differ
Files smallinitrd/lib/modules/4.12.13/modules.symbols and biginitrd/lib/modules/4.12.13/modules.symbols differ
Files smallinitrd/lib/modules/4.12.13/modules.symbols.bin and biginitrd/lib/modules/4.12.13/modules.symbols.bin differ
Only in biginitrd/lib/udev/rules.d: 56-lvm.rules
Only in biginitrd/lib/udev/rules.d: 69-lvm-metad.rules
Only in biginitrd/lib/udev/rules.d: 99-openmediavault-md-raid.rules
Only in biginitrd/lib/udev/rules.d: 99-openmediavault-nonrot.rules
Only in biginitrd/lib/udev/rules.d: 99-openmediavault-scheduler.rules
Only in biginitrd/sbin: lvm
Only in biginitrd/sbin: micro-evtd
Only in biginitrd/sbin: mount.fuse
Only in biginitrd/sbin: mount.ntfs
Only in biginitrd/sbin: mount.ntfs-3g
Only in biginitrd/sbin: vgchange
Only in biginitrd/scripts/init-bottom: early_swap.sh
Files smallinitrd/scripts/init-bottom/ORDER and biginitrd/scripts/init-bottom/ORDER differ
Only in biginitrd/scripts/init-top: enable_serial.sh
Files smallinitrd/scripts/init-top/ORDER and biginitrd/scripts/init-top/ORDER differ
Only in biginitrd/scripts/local-block: lvm2
Files smallinitrd/scripts/local-block/ORDER and biginitrd/scripts/local-block/ORDER differ
Only in biginitrd/scripts/local-bottom: ntfs_3g
Files smallinitrd/scripts/local-bottom/ORDER and biginitrd/scripts/local-bottom/ORDER differ
Only in biginitrd/scripts/local-premount: btrfs
Only in biginitrd/scripts/local-premount: ntfs_3g
Files smallinitrd/scripts/local-premount/ORDER and biginitrd/scripts/local-premount/ORDER differ
Only in biginitrd/scripts: local-top
Only in biginitrd/usr/bin: btrfs
Only in biginitrd/usr/bin: ntfs-3g
Only in biginitrd/usr/lib/arm-linux-gnueabi: libaio.so.1
Only in biginitrd/usr/lib/arm-linux-gnueabi: libaio.so.1.0.1
Only in biginitrd/usr/lib/arm-linux-gnueabi: libdevmapper-event.so.1.02.1
Only in biginitrd/usr/lib/arm-linux-gnueabi: libgcc_s.so.1
Only in biginitrd/usr/lib/arm-linux-gnueabi: libgcrypt.so.20
Only in biginitrd/usr/lib/arm-linux-gnueabi: libgcrypt.so.20.2.4
Only in biginitrd/usr/lib/arm-linux-gnueabi: libgpg-error.so.0
Only in biginitrd/usr/lib/arm-linux-gnueabi: libgpg-error.so.0.26.1
Only in biginitrd/usr/lib/arm-linux-gnueabi: liblz4.so.1
Only in biginitrd/usr/lib/arm-linux-gnueabi: liblz4.so.1.8.3
Only in biginitrd/usr/lib/arm-linux-gnueabi: liblzo2.so.2
Only in biginitrd/usr/lib/arm-linux-gnueabi: liblzo2.so.2.0.0
Only in biginitrd/usr/lib/arm-linux-gnueabi: libntfs-3g.so.883
Only in biginitrd/usr/lib/arm-linux-gnueabi: libntfs-3g.so.883.0.0
Only in biginitrd/usr/lib/arm-linux-gnueabi: libreadline.so.5
Only in biginitrd/usr/lib/arm-linux-gnueabi: libreadline.so.5.2
Only in biginitrd/usr/lib/arm-linux-gnueabi: libsystemd.so.0
Only in biginitrd/usr/lib/arm-linux-gnueabi: libsystemd.so.0.25.0
Only in biginitrd/usr/lib/arm-linux-gnueabi: libtinfo.so.6
Only in biginitrd/usr/lib/arm-linux-gnueabi: libtinfo.so.6.1
Only in biginitrd/usr/lib/arm-linux-gnueabi: libz.so.1
Only in biginitrd/usr/lib/arm-linux-gnueabi: libz.so.1.2.11
Only in biginitrd/usr/lib/arm-linux-gnueabi: libzstd.so.1
Only in biginitrd/usr/lib/arm-linux-gnueabi: libzstd.so.1.3.8
Only in biginitrd/usr/lib/modules/4.12.13/kernel/drivers/md: dm-bufio.ko
Only in biginitrd/usr/lib/modules/4.12.13/kernel/drivers/md: dm-log.ko
Only in biginitrd/usr/lib/modules/4.12.13/kernel/drivers/md: dm-mirror.ko
Only in biginitrd/usr/lib/modules/4.12.13/kernel/drivers/md: dm-raid.ko
Only in biginitrd/usr/lib/modules/4.12.13/kernel/drivers/md: dm-region-hash.ko
Only in biginitrd/usr/lib/modules/4.12.13/kernel/drivers/md: dm-snapshot.ko
Only in biginitrd/usr/lib/modules/4.12.13/kernel/fs: fuse
Files smallinitrd/usr/lib/modules/4.12.13/modules.alias and biginitrd/usr/lib/modules/4.12.13/modules.alias differ
Files smallinitrd/usr/lib/modules/4.12.13/modules.alias.bin and biginitrd/usr/lib/modules/4.12.13/modules.alias.bin differ
Files smallinitrd/usr/lib/modules/4.12.13/modules.dep and biginitrd/usr/lib/modules/4.12.13/modules.dep differ
Files smallinitrd/usr/lib/modules/4.12.13/modules.dep.bin and biginitrd/usr/lib/modules/4.12.13/modules.dep.bin differ
Files smallinitrd/usr/lib/modules/4.12.13/modules.devname and biginitrd/usr/lib/modules/4.12.13/modules.devname differ
Files smallinitrd/usr/lib/modules/4.12.13/modules.symbols and biginitrd/usr/lib/modules/4.12.13/modules.symbols differ
Files smallinitrd/usr/lib/modules/4.12.13/modules.symbols.bin and biginitrd/usr/lib/modules/4.12.13/modules.symbols.bin differ
Only in biginitrd/usr/lib/udev/rules.d: 56-lvm.rules
Only in biginitrd/usr/lib/udev/rules.d: 69-lvm-metad.rules
Only in biginitrd/usr/lib/udev/rules.d: 99-openmediavault-md-raid.rules
Only in biginitrd/usr/lib/udev/rules.d: 99-openmediavault-nonrot.rules
Only in biginitrd/usr/lib/udev/rules.d: 99-openmediavault-scheduler.rules
Only in biginitrd/usr/sbin: lvm
Only in biginitrd/usr/sbin: micro-evtd
Only in biginitrd/usr/sbin: mount.fuse
Only in biginitrd/usr/sbin: mount.ntfs
Only in biginitrd/usr/sbin: mount.ntfs-3g
Only in biginitrd/usr/sbin: vgchange
root@terastation:/boot# diff -qyr smallinitrd/ biginitrd/
Only in biginitrd/bin: btrfs
Only in biginitrd/bin: ntfs-3g
Only in biginitrd/conf/conf.d: compress
Only in biginitrd/conf/conf.d: zz-resume-auto
Files smallinitrd/conf/initramfs.conf and biginitrd/conf/initramfs.conf differ
Files smallinitrd/etc/ld.so.cache and biginitrd/etc/ld.so.cache differ
Only in biginitrd/etc: lvm
Files smallinitrd/etc/mdadm/mdadm.conf and biginitrd/etc/mdadm/mdadm.conf differ
Only in biginitrd/etc/modprobe.d: openmediavault.conf
Only in smallinitrd/: initrd.img-4.12.13
Only in biginitrd/: intrd
Only in biginitrd/lib/arm-linux-gnueabi: libaio.so.1
Only in biginitrd/lib/arm-linux-gnueabi: libaio.so.1.0.1
Only in biginitrd/lib/arm-linux-gnueabi: libdevmapper-event.so.1.02.1
Only in biginitrd/lib/arm-linux-gnueabi: libgcc_s.so.1
Only in biginitrd/lib/arm-linux-gnueabi: libgcrypt.so.20
Only in biginitrd/lib/arm-linux-gnueabi: libgcrypt.so.20.2.4
Only in biginitrd/lib/arm-linux-gnueabi: libgpg-error.so.0
Only in biginitrd/lib/arm-linux-gnueabi: libgpg-error.so.0.26.1
Only in biginitrd/lib/arm-linux-gnueabi: liblz4.so.1
Only in biginitrd/lib/arm-linux-gnueabi: liblz4.so.1.8.3
Only in biginitrd/lib/arm-linux-gnueabi: liblzo2.so.2
Only in biginitrd/lib/arm-linux-gnueabi: liblzo2.so.2.0.0
Only in biginitrd/lib/arm-linux-gnueabi: libntfs-3g.so.883
Only in biginitrd/lib/arm-linux-gnueabi: libntfs-3g.so.883.0.0
Only in biginitrd/lib/arm-linux-gnueabi: libreadline.so.5
Only in biginitrd/lib/arm-linux-gnueabi: libreadline.so.5.2
Only in biginitrd/lib/arm-linux-gnueabi: libsystemd.so.0
Only in biginitrd/lib/arm-linux-gnueabi: libsystemd.so.0.25.0
Only in biginitrd/lib/arm-linux-gnueabi: libtinfo.so.6
Only in biginitrd/lib/arm-linux-gnueabi: libtinfo.so.6.1
Only in biginitrd/lib/arm-linux-gnueabi: libz.so.1
Only in biginitrd/lib/arm-linux-gnueabi: libz.so.1.2.11
Only in biginitrd/lib/arm-linux-gnueabi: libzstd.so.1
Only in biginitrd/lib/arm-linux-gnueabi: libzstd.so.1.3.8
Only in biginitrd/lib/modules/4.12.13/kernel/drivers/md: dm-bufio.ko
Only in biginitrd/lib/modules/4.12.13/kernel/drivers/md: dm-log.ko
Only in biginitrd/lib/modules/4.12.13/kernel/drivers/md: dm-mirror.ko
Only in biginitrd/lib/modules/4.12.13/kernel/drivers/md: dm-raid.ko
Only in biginitrd/lib/modules/4.12.13/kernel/drivers/md: dm-region-hash.ko
Only in biginitrd/lib/modules/4.12.13/kernel/drivers/md: dm-snapshot.ko
Only in biginitrd/lib/modules/4.12.13/kernel/fs: fuse
Files smallinitrd/lib/modules/4.12.13/modules.alias and biginitrd/lib/modules/4.12.13/modules.alias differ
Files smallinitrd/lib/modules/4.12.13/modules.alias.bin and biginitrd/lib/modules/4.12.13/modules.alias.bin differ
Files smallinitrd/lib/modules/4.12.13/modules.dep and biginitrd/lib/modules/4.12.13/modules.dep differ
Files smallinitrd/lib/modules/4.12.13/modules.dep.bin and biginitrd/lib/modules/4.12.13/modules.dep.bin differ
Files smallinitrd/lib/modules/4.12.13/modules.devname and biginitrd/lib/modules/4.12.13/modules.devname differ
Files smallinitrd/lib/modules/4.12.13/modules.symbols and biginitrd/lib/modules/4.12.13/modules.symbols differ
Files smallinitrd/lib/modules/4.12.13/modules.symbols.bin and biginitrd/lib/modules/4.12.13/modules.symbols.bin differ
Only in biginitrd/lib/udev/rules.d: 56-lvm.rules
Only in biginitrd/lib/udev/rules.d: 69-lvm-metad.rules
Only in biginitrd/lib/udev/rules.d: 99-openmediavault-md-raid.rules
Only in biginitrd/lib/udev/rules.d: 99-openmediavault-nonrot.rules
Only in biginitrd/lib/udev/rules.d: 99-openmediavault-scheduler.rules
Only in biginitrd/sbin: lvm
Only in biginitrd/sbin: micro-evtd
Only in biginitrd/sbin: mount.fuse
Only in biginitrd/sbin: mount.ntfs
Only in biginitrd/sbin: mount.ntfs-3g
Only in biginitrd/sbin: vgchange
Only in biginitrd/scripts/init-bottom: early_swap.sh
Files smallinitrd/scripts/init-bottom/ORDER and biginitrd/scripts/init-bottom/ORDER differ
Only in biginitrd/scripts/init-top: enable_serial.sh
Files smallinitrd/scripts/init-top/ORDER and biginitrd/scripts/init-top/ORDER differ
Only in biginitrd/scripts/local-block: lvm2
Files smallinitrd/scripts/local-block/ORDER and biginitrd/scripts/local-block/ORDER differ
Only in biginitrd/scripts/local-bottom: ntfs_3g
Files smallinitrd/scripts/local-bottom/ORDER and biginitrd/scripts/local-bottom/ORDER differ
Only in biginitrd/scripts/local-premount: btrfs
Only in biginitrd/scripts/local-premount: ntfs_3g
Files smallinitrd/scripts/local-premount/ORDER and biginitrd/scripts/local-premount/ORDER differ
Only in biginitrd/scripts: local-top
Only in biginitrd/usr/bin: btrfs
Only in biginitrd/usr/bin: ntfs-3g
Only in biginitrd/usr/lib/arm-linux-gnueabi: libaio.so.1
Only in biginitrd/usr/lib/arm-linux-gnueabi: libaio.so.1.0.1
Only in biginitrd/usr/lib/arm-linux-gnueabi: libdevmapper-event.so.1.02.1
Only in biginitrd/usr/lib/arm-linux-gnueabi: libgcc_s.so.1
Only in biginitrd/usr/lib/arm-linux-gnueabi: libgcrypt.so.20
Only in biginitrd/usr/lib/arm-linux-gnueabi: libgcrypt.so.20.2.4
Only in biginitrd/usr/lib/arm-linux-gnueabi: libgpg-error.so.0
Only in biginitrd/usr/lib/arm-linux-gnueabi: libgpg-error.so.0.26.1
Only in biginitrd/usr/lib/arm-linux-gnueabi: liblz4.so.1
Only in biginitrd/usr/lib/arm-linux-gnueabi: liblz4.so.1.8.3
Only in biginitrd/usr/lib/arm-linux-gnueabi: liblzo2.so.2
Only in biginitrd/usr/lib/arm-linux-gnueabi: liblzo2.so.2.0.0
Only in biginitrd/usr/lib/arm-linux-gnueabi: libntfs-3g.so.883
Only in biginitrd/usr/lib/arm-linux-gnueabi: libntfs-3g.so.883.0.0
Only in biginitrd/usr/lib/arm-linux-gnueabi: libreadline.so.5
Only in biginitrd/usr/lib/arm-linux-gnueabi: libreadline.so.5.2
Only in biginitrd/usr/lib/arm-linux-gnueabi: libsystemd.so.0
Only in biginitrd/usr/lib/arm-linux-gnueabi: libsystemd.so.0.25.0
Only in biginitrd/usr/lib/arm-linux-gnueabi: libtinfo.so.6
Only in biginitrd/usr/lib/arm-linux-gnueabi: libtinfo.so.6.1
Only in biginitrd/usr/lib/arm-linux-gnueabi: libz.so.1
Only in biginitrd/usr/lib/arm-linux-gnueabi: libz.so.1.2.11
Only in biginitrd/usr/lib/arm-linux-gnueabi: libzstd.so.1
Only in biginitrd/usr/lib/arm-linux-gnueabi: libzstd.so.1.3.8
Only in biginitrd/usr/lib/modules/4.12.13/kernel/drivers/md: dm-bufio.ko
Only in biginitrd/usr/lib/modules/4.12.13/kernel/drivers/md: dm-log.ko
Only in biginitrd/usr/lib/modules/4.12.13/kernel/drivers/md: dm-mirror.ko
Only in biginitrd/usr/lib/modules/4.12.13/kernel/drivers/md: dm-raid.ko
Only in biginitrd/usr/lib/modules/4.12.13/kernel/drivers/md: dm-region-hash.ko
Only in biginitrd/usr/lib/modules/4.12.13/kernel/drivers/md: dm-snapshot.ko
Only in biginitrd/usr/lib/modules/4.12.13/kernel/fs: fuse
Files smallinitrd/usr/lib/modules/4.12.13/modules.alias and biginitrd/usr/lib/modules/4.12.13/modules.alias differ
Files smallinitrd/usr/lib/modules/4.12.13/modules.alias.bin and biginitrd/usr/lib/modules/4.12.13/modules.alias.bin differ
Files smallinitrd/usr/lib/modules/4.12.13/modules.dep and biginitrd/usr/lib/modules/4.12.13/modules.dep differ
Files smallinitrd/usr/lib/modules/4.12.13/modules.dep.bin and biginitrd/usr/lib/modules/4.12.13/modules.dep.bin differ
Files smallinitrd/usr/lib/modules/4.12.13/modules.devname and biginitrd/usr/lib/modules/4.12.13/modules.devname differ
Files smallinitrd/usr/lib/modules/4.12.13/modules.symbols and biginitrd/usr/lib/modules/4.12.13/modules.symbols differ
Files smallinitrd/usr/lib/modules/4.12.13/modules.symbols.bin and biginitrd/usr/lib/modules/4.12.13/modules.symbols.bin differ
Only in biginitrd/usr/lib/udev/rules.d: 56-lvm.rules
Only in biginitrd/usr/lib/udev/rules.d: 69-lvm-metad.rules
Only in biginitrd/usr/lib/udev/rules.d: 99-openmediavault-md-raid.rules
Only in biginitrd/usr/lib/udev/rules.d: 99-openmediavault-nonrot.rules
Only in biginitrd/usr/lib/udev/rules.d: 99-openmediavault-scheduler.rules
Only in biginitrd/usr/sbin: lvm
Only in biginitrd/usr/sbin: micro-evtd
Only in biginitrd/usr/sbin: mount.fuse
Only in biginitrd/usr/sbin: mount.ntfs
Only in biginitrd/usr/sbin: mount.ntfs-3g
Only in biginitrd/usr/sbin: vgchange
```

**Comment by vKnmnn** [comment]
Steps to install OMV so far:
- install debian_on_buffalo
- reboot a few times
- remove existing swap
- add a usb device as swap
- readd swap from /dev/md
- disable OOM killer with sysctl command
- back up /boot dir
- run debian installer according to their docs

**Comment by 1000001101000** [comment]
I would assume that OMV must be adding initramfs hooks to load all this junk. i would look through /etc/initramfs-tools and /usr/share/initramfs-tools/.

I have heard from others that lvm adds a lot to the initrd. 
if you're using raid for the rootfs the mdadm stuff will add some too but can't be avoided. 
I believe a lot of the libcrypto stuff is required for newer versions of kmod for loading signed kernel modules or something despite the armel kernel not using that feature. Downgrading kmod to the stretch version can reclaim a bunch of initrd space if needed.
raid5/6 end up requiring a lot of CPU on these devices because of lack of accelerated XOR and generally low CPU power. It should probably be avoided if you plan to run other things.

changing the commandline is tricky, requiring either modifying uboot or compiling it into a custom kernel. there is usually another way to set such settings which is typically what I would recommend. you could even add a script to do it in the initrd if it needs to happen really early.

I don't know what you are refering to for the 20mb from uboot.

**Comment by 1000001101000** [comment]
what do you want OMV for anyway?

**Comment by vKnmnn** [comment]
i want OMV so i don't have to implement all those features you would want for an offsite-backup station.
It should be mostly fire and forget. set an array, have a raspberry open a vpn (or do it from the device), and just rsync or cronopete or amanda files over there.
that's the easy part. 
NAS-OSes come with monitoring options, they send mails, when the array breaks et cetera. i'd rather not build my own full-fledged nas-OS, if you know what i mean.

I don't really care about CPU usage, as traffic to the nas will be moderate (max 3MB) anyway and i'm not planning on running 20 docker containers on it.

i could really try it with an initrd script. i will.

the 20MB from uboot -> 
```
U-Boot 1.1.1 (Oct 19 2008 - 21:02:54) Marvell version: 1.12.1 - TINY
Buffalo Version: 1.19-1.00

DRAM CS[0] base 0x00000000   size 128MB 
DRAM Total size 128MB 
[256kB@fffc0000] Flash: 256 kB
Addresses 20M - 0M are saved for the U-Boot usage.
Mem malloc Initialization (20M - 16M): Done
```

**Comment by 1000001101000** [comment]
makes sense. 

I think that allocation only applies while uboot is running and that the kernel will already be taking care of that. Mine doesn't appear to be missing any memory when booted.

**Comment by vKnmnn** [comment]
None of the alternatives are viable

FreeNas -> BSD, 
Nas4Free -> no ARM
Amahi -> no ARM
Rockbox -> high requirements
Openfiler -> no sources

**Comment by vKnmnn** [comment]
i see, didn't check that.

**Comment by 1000001101000** [comment]
yeah, I'm perpetually disappointment there isn't something like a lighter-weight OMV/webmin type system that would work on these systems. I'd have thought something designed for the original raspberry pi but a lot of that stuff is graphical based. 

I did try running an xserver on an ls210 with somebody to test something. it worked better than I would have expected though still not great (and that was without a window manager). I don't know of any great gtk/qt apps to do the type of stuff you want either but if you knew of one it

**Comment by vKnmnn** [comment]
I'm giving up.
I'll stick with plain old debian.

still some questions:
is there a way to make the fan spin down in depence of the temperature?
is there an easy way to send strings to the display from the shell?

**Comment by 1000001101000** [comment]
I put together a "fan daemon" which should have been installed by default. I have some info about it here:
https://github.com/1000001101000/Debian_on_Buffalo/wiki/Post-Installation-Options#Microcontroller_Fans

I've documented (somewhat) the protocol used to communicate with the microcontroller that controls the lcd/fans/buzzer/leds/etc. The technical info can be found here:
https://buffalonas.miraheze.org/wiki/Terastation_Microcontroller_Interface 

I also created a python library for controlling it:
https://github.com/1000001101000/Python_buffalo_libmicon

The lcd can be set with:
```
#!/usr/bin/python3

import libmicon

test = libmicon.micon_api("/dev/ttyS1")
test.set_lcd_buffer(0x90,"Line 1","Line 2")
test.cmd_force_lcd_disp(libmicon.lcd_disp_buffer0)
test.send_write_cmd(1,libmicon.lcd_set_dispitem,0x20)
test.set_lcd_brightness(libmicon.LCD_BRIGHT_FULL)
test.port.close()
quit()
```
I also added lcd support to the older micro-evtd tool so that I could set it within the installer:
https://github.com/1000001101000/micro-evtd
```
## set lcd display to installer message
micro-evtd -s 20905465726173746174696f6e2061726d2044656269616e20496e7374616c6c657231,0025,013220,013aff
```

**Comment by vKnmnn** [comment]
Thank you, that helps.
I'm wondering if the temperature is actually correct. The fan has been on 3 the whole time, yet the temperature is at 41 degrees, supposedly.

**Comment by 1000001101000** [comment]
Good question. I don't even know where the sensor is to be honest. I assume it's either internal to the microcontroller or nearby it on the board somewhere.

For the non-rackmount  devices I set the threshold for full speed fairly low since those fans aren't usually all that loud. I really only developed it because the rack devices are ridiculously loud. You should be able to adjust the thresholds to match your needs. You could even write something more sophisticated that takes drive temperature into account.

**Comment by vKnmnn** [comment]
I might take a look.
You might wanna have a look at webmin. Seems like it might be what we're looking for.

**Comment by 1000001101000** [comment]
I tried webmin on the TS-XEL and it locked up installing modules. Admittedly, I didn’t put any effort into troubleshooting. Hopefully you can figure out how to get it working.

I seem to remember the install process was far less painful than OMV

**Comment by vKnmnn** [comment]
installation went fine for me, took a very long time though.
it seems to be working. i have looked at it just for a few minutes and found some problems with the smartctl page.
I have to take a break from this for a few days though.

**Comment by 1000001101000** [comment]
Is there anything else you want me to look at for this?

I'm looking to close out some issues.

**Comment by vKnmnn** [comment]
i'm good for now, thanks :)
